[package]
name = "A_Vanya_and_Fence"
version = "0.1.0"
authors = ["Dave Fol <dof5@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
